"""
Pydantic models for Obsidian entity frontmatter.

These models match EXACTLY what currently exists in the Obsidian vault templates.
They use `extra = "allow"` for forward compatibility with additional fields.

Entity Types:
    - Person: Contact/person notes (@Name.md files)
    - Company: Organization notes (@CompanyName.md files)
    - Book: Reading list items (Title - Author.md files)
    - Watch: Films/series to watch
    - Explore: Links/topics to explore
    - GiftIdea: Gift ideas for people
    - Meeting: Meeting notes (generated by Exocortex)
"""

from typing import List, Optional, Literal, Union, Type
from datetime import date
from pydantic import BaseModel, ConfigDict, Field


class BaseEntity(BaseModel):
    """
    Base class for all Obsidian entity types.

    Allows extra fields for forward compatibility - any fields in the
    frontmatter that aren't in the model will be preserved.
    """

    model_config = ConfigDict(
        extra="allow",
        # Use enum values when serializing
        use_enum_values=True,
        # Allow population by field name or alias
        populate_by_name=True,
    )

    type: str
    tags: List[str] = Field(default_factory=list)


class Person(BaseEntity):
    """
    Person entity - represents a contact in the vault.

    Matches the person.md template:
        type: person
        name: ""
        aliases: []
        emails: []
        phones: []
        whatsapp: ""
        company: ""
        title: ""
        linkedin: ""
        roles: []
        tags: [person]
        created: "{{date}}"

    Roles:
        Array of role identifiers that modify assistant behavior for this contact.
        Roles affect priority levels, staleness thresholds, notification preferences,
        and trigger special behaviors (e.g., agenda generation for coaching clients).

        Defined roles: vip, coaching-client, family, investor, active

        Combination rules: When a person has multiple roles, the most restrictive
        staleness threshold applies, priority modifiers are additive (capped at p1),
        notifications are union (any role enables = enabled), and all special
        behaviors apply.
    """

    type: Literal["person"] = "person"
    name: str = ""
    aliases: List[str] = Field(default_factory=list)
    emails: List[str] = Field(default_factory=list)
    phones: List[str] = Field(default_factory=list)
    whatsapp: str = ""
    company: str = ""
    title: str = ""
    linkedin: str = ""
    roles: List[str] = Field(default_factory=list)
    created: str = ""

    def get_primary_email(self) -> Optional[str]:
        """Get the first email address if available."""
        return self.emails[0] if self.emails else None

    def get_primary_phone(self) -> Optional[str]:
        """Get the first phone number if available."""
        return self.phones[0] if self.phones else None

    def has_role(self, role: str) -> bool:
        """Check if person has a specific role."""
        return role in self.roles

    def has_any_role(self, *roles: str) -> bool:
        """Check if person has any of the specified roles."""
        return any(r in self.roles for r in roles)

    def to_entity_id(self) -> str:
        """Generate a stable entity ID for graph databases."""
        return f"person_{self.name.lower().replace(' ', '_')}"


class Company(BaseEntity):
    """
    Company entity - represents an organization in the vault.

    Matches the company.md template:
        type: company
        name: ""
        website: ""
        industry: ""
        linkedin: ""
        tags: [company]
        created: "{{date}}"
    """

    type: Literal["company"] = "company"
    name: str = ""
    website: str = ""
    industry: str = ""
    linkedin: str = ""
    created: str = ""

    def to_entity_id(self) -> str:
        """Generate a stable entity ID for graph databases."""
        return f"company_{self.name.lower().replace(' ', '_').replace('-', '_')}"


class Book(BaseEntity):
    """
    Book entity - represents a book in the reading list.

    Matches the book.md template:
        type: book
        title: ""
        author: ""
        description: ""
        status: to-read  # to-read, reading, read, abandoned
        rating: ""
        isbn: ""
        publisher: ""
        publication_year: ""
        tags: [book]
        source_url: ""
        date_added: "{{date}}"
        date_finished: ""
    """

    type: Literal["book"] = "book"
    title: str = ""
    author: str = ""
    description: str = ""
    status: str = "to-read"  # to-read, reading, read, abandoned
    rating: str = ""
    isbn: str = ""
    publisher: str = ""
    publication_year: str = ""
    source_url: str = ""
    date_added: str = ""
    date_finished: str = ""


class Watch(BaseEntity):
    """
    Watch entity - represents a film/series to watch.

    Matches the watch.md template:
        type: watch
        title: ""
        media_type: ""  # film, series, documentary
        director: ""
        year: ""
        status: to-watch  # to-watch, watching, watched, abandoned
        rating: ""
        streaming_service: ""
        recommended_by: ""
        tags: [watch]
        date_added: "{{date}}"
        date_watched: ""
    """

    type: Literal["watch"] = "watch"
    title: str = ""
    media_type: str = ""  # film, series, documentary
    director: str = ""
    year: str = ""
    status: str = "to-watch"  # to-watch, watching, watched, abandoned
    rating: str = ""
    streaming_service: str = ""
    recommended_by: str = ""
    date_added: str = ""
    date_watched: str = ""


class Explore(BaseEntity):
    """
    Explore entity - represents a link/topic to explore.

    Matches the explore.md template:
        type: explore
        subtype: ""  # link, topic, idea, someday
        title: ""
        url: ""
        source: ""  # where you found it / who mentioned it
        status: captured  # captured, exploring, processed, archived
        tags: [explore]
        created: "{{date}}"
    """

    type: Literal["explore"] = "explore"
    subtype: str = ""  # link, topic, idea, someday
    title: str = ""
    url: str = ""
    source: str = ""  # where you found it / who mentioned it
    status: str = "captured"  # captured, exploring, processed, archived
    created: str = ""


class GiftIdea(BaseEntity):
    """
    Gift idea entity - represents a gift idea for someone.

    Matches the Gift Idea.md template:
        type: gift-idea
        for:
        source:
        date_added: "{{date}}"
    """

    type: Literal["gift-idea"] = "gift-idea"
    # Note: 'for' is a Python keyword, so we use an alias
    for_person: str = Field(default="", alias="for")
    source: str = ""
    date_added: str = ""


class Meeting(BaseEntity):
    """
    Meeting entity - represents a meeting note (generated by Exocortex).

    This is generated by the transcript processor, not a template:
        type: meeting
        date: ""
        attendees: []
        topics: []
        meeting_id: ""
    """

    type: Literal["meeting"] = "meeting"
    date: str = ""
    attendees: List[str] = Field(default_factory=list)
    topics: List[str] = Field(default_factory=list)
    meeting_id: str = ""


# Type alias for all entity types
EntityType = Union[Person, Company, Book, Watch, Explore, GiftIdea, Meeting]

# Mapping from type string to model class
TYPE_TO_MODEL: dict[str, Type[BaseEntity]] = {
    "person": Person,
    "company": Company,
    "book": Book,
    "watch": Watch,
    "explore": Explore,
    "gift-idea": GiftIdea,
    "meeting": Meeting,
}


def get_model_for_type(type_name: str) -> Optional[Type[BaseEntity]]:
    """
    Get the Pydantic model class for a given type name.

    Args:
        type_name: The 'type' field value from frontmatter

    Returns:
        The corresponding model class, or None if unknown
    """
    return TYPE_TO_MODEL.get(type_name)
