"""The frozen fixture corpus and its DECLARED oracle (WI-016).

CORPUS_COUPLING: this module is the sole reader of `tests/fixtures/vault/`; it
pins nothing in `docs/**` and derives no member by proxy — the manifest names
every note by its exact filename and the digest is over frozen bytes.

Three things and no test logic: the DECLARED manifest, the frozen digest, and
`materialize_vault`. Every value in `NOTES[...].fields` is HAND-WRITTEN from the
model definitions in `obsidian_schemas/models.py` and never produced by running
the parser — a manifest generated by parsing the corpus asserts only that the
parser agrees with itself. Where a note declares a SUBSET of its model's fields,
the subset is the declaration and the checks assert agreement on exactly it; the
eight `roundtrip_representative` notes declare their model's whole field set,
which is what makes AC-2's round trip total for them.

Load-bearing external dependency: AC-5(b) admits an identity-position token
whose `str.lower()` is in `obsidian_schemas.name_cleaning._GENERIC_ORG_SUFFIXES`
(name_cleaning.py:58) with no pool row. An edit THERE widens this module's
privacy admission with no AC change. Read that set before adding to it.

Regenerating CORPUS_DIGEST after a deliberate corpus edit — one line, from the
repo root, and deliberately a speed bump rather than a puzzle:

    .venv/bin/python -c "import sys; sys.path.insert(0, '.'); \
        from tests.fixture_vault import corpus_digest; print(corpus_digest())"
"""

import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from obsidian_schemas.repositories.base import (
    MALFORMED_FRONTMATTER,
    SCHEMA_DRIFT,
    UNREADABLE,
)

CORPUS_ROOT = Path(__file__).resolve().parent / "fixtures" / "vault"

#: `sha256` over the sorted sequence of (corpus-relative POSIX path, file bytes),
#: each field NUL-framed. Editing, adding or deleting any fixture note without
#: regenerating this constant is RED (AC-1(a)).
CORPUS_DIGEST = "05e732ebce5a64678000c4af00f7cdfced906546de356c861bd3042940d44d17"

#: The ONE ISBN placeholder the corpus uses (Design §6.4). An ISBN-13 is a
#: 13-digit run the phone predicate matches and an ISBN has no reserved range to
#: move into, so it is exempted by EQUALITY against this one-member literal —
#: which cannot be padded and imposes no obligation over anything unauthored.
RESERVED_ISBN = "9780000000001"


@dataclass(frozen=True)
class Verdict:
    """What a corruption specimen must produce, declared rather than observed."""

    kind: str            # "refusal" | "cleaned" | "loads"
    pattern: str = ""    # kind == "refusal": the NameGateRefusal.pattern expected
    cleaned: str = ""    # kind == "cleaned": clean_person_name's expected output


@dataclass(frozen=True)
class NoteSpec:
    """One corpus member's declared oracle.

    `shape_classes` and `discriminator` are two fields because AC-1(c) and
    AC-3(i) ask two different questions. AC-1(c) asks whether a note whose
    stored `name:` trips a live Tier-1 branch is present and NAMED as such — a
    fact about the DOOR, true whatever the live vault holds. AC-3(i) asks
    whether the corpus's declared class coverage equals the census's MEASURED
    rows — a fact about the VAULT. The landed census rules `arrow_connective`
    and `path_hostile` ABSENT, so one field could not answer both.
    """

    declared_type: Optional[str]
    fields: Optional[dict] = None
    undeclared: dict = field(default_factory=dict)
    shape_classes: tuple = ()
    discriminator: str = ""
    verdict: Optional[Verdict] = None
    roundtrip_representative: bool = False
    raw_bytes_hex: Optional[str] = None


def _person(name, **overrides):
    """A person note's declared fields. The defaults are `models.py:79-90`'s own,
    hand-transcribed once; `overrides` are the values that note actually sets."""
    declared = {
        "type": "person",
        "name": name,
        "aliases": [],
        "emails": [],
        "phones": [],
        "whatsapp": "",
        "company": "",
        "title": "",
        "linkedin": "",
        "slack": "",
        "roles": [],
        "birthday": "",
        "created": "2026-01-04",
        "tags": ["person"],
    }
    declared.update(overrides)
    return declared


def _company(name, **overrides):
    declared = {
        "type": "company",
        "name": name,
        "website": "",
        "industry": "",
        "linkedin": "",
        "created": "2026-01-04",
        "tags": ["company"],
    }
    declared.update(overrides)
    return declared


def _meeting(date, attendees, topics, meeting_id):
    return {
        "type": "meeting",
        "date": date,
        "attendees": attendees,
        "topics": topics,
        "meeting_id": meeting_id,
        "tags": ["meeting"],
    }


def _book(title, author, **overrides):
    declared = {
        "type": "book",
        "title": title,
        "author": author,
        "description": "",
        "status": "to-read",
        "rating": "",
        "isbn": "",
        "publisher": "",
        "publication_year": "",
        "source_url": "",
        "date_added": "2026-01-04",
        "date_finished": "",
        "tags": ["book"],
    }
    declared.update(overrides)
    return declared


def _watch(title, **overrides):
    declared = {
        "type": "watch",
        "title": title,
        "media_type": "",
        "director": "",
        "year": "",
        "status": "to-watch",
        "rating": "",
        "streaming_service": "",
        "recommended_by": "",
        "date_added": "2026-01-04",
        "date_watched": "",
        "tags": ["watch"],
    }
    declared.update(overrides)
    return declared


def _explore(title, **overrides):
    declared = {
        "type": "explore",
        "subtype": "",
        "title": title,
        "url": "",
        "source": "",
        "status": "captured",
        "created": "2026-01-04",
        "tags": ["explore"],
    }
    declared.update(overrides)
    return declared


def _gift(for_person, source):
    return {
        "type": "gift-idea",
        "for_person": for_person,
        "source": source,
        "date_added": "2026-01-04",
        "tags": ["gift-idea"],
    }


def _exploration(title, **overrides):
    declared = {
        "type": "exploration",
        "title": title,
        "status": "active",
        "created": "2026-01-04",
        "updated": "2026-02-01",
        "related": [],
        "origin": "",
        "graduated_to": "",
        "abandoned_reason": "",
        "tags": ["exploration"],
    }
    declared.update(overrides)
    return declared


#: Keyed by CORPUS-RELATIVE filename — the corpus is one flat directory, so a
#: corpus-relative POSIX path IS the bare filename, which is what makes AC-1(b)'s
#: digest-over-the-materialized-tree a real assertion.
NOTES: dict = {
    # ---- person -----------------------------------------------------------
    "@Thrandell Ibberly.md": NoteSpec(
        declared_type="person",
        fields=_person(
            "Thrandell Ibberly",
            emails=["thrandell@example.com"],
            phones=["+44 7700 900123"],
            whatsapp="447700900789@example.com",
            company="Voxleaf Ltd",
            title="director",
            slack="@thrandell",
            roles=["vip"],
            birthday="04-07",
        ),
        roundtrip_representative=True,
    ),
    "@Søréna Kelmarrä.md": NoteSpec(
        declared_type="person",
        fields=_person("Søréna Kelmarrä"),
        shape_classes=("diacritics",),
        verdict=Verdict(kind="loads"),
    ),
    "@Oskaline Brenvik-Tarnquil.md": NoteSpec(
        declared_type="person",
        fields=_person("Oskaline Brenvik-Tarnquil"),
        shape_classes=("hyphenated_surname",),
        verdict=Verdict(kind="loads"),
    ),
    "@Dave  Marrowyn Fennwick.md": NoteSpec(
        declared_type="person",
        fields=_person("Dave  Marrowyn Fennwick"),
        shape_classes=("whitespace_damage",),
        # `clean_person_name` strips no prefix here (`_CALENDAR_PREFIX_RE` wants a
        # `-` or `/` after Dave) and collapses the double space at its final
        # `\s{2,}` normalize — `name_cleaning.py`, read arm by arm.
        verdict=Verdict(kind="cleaned", cleaned="Dave Marrowyn Fennwick"),
    ),
    "@Quillam Ostrivane.md": NoteSpec(
        declared_type="person",
        fields=_person("Quillam Ostrivane Lumbrek"),
        shape_classes=("stem_name_divergence",),
        verdict=Verdict(kind="loads"),
    ),
    "@Quillam Lumbrek.md": NoteSpec(
        declared_type="person",
        fields=_person("Quillam Ostrivane Lumbrek"),
        shape_classes=("stem_name_divergence",),
        verdict=Verdict(kind="loads"),
    ),
    # The third member of the three-filename collision §1.3 rule 5 mandates. It
    # is declared under `stem_name_divergence` and NEVER as a
    # `same_name_collision` specimen: the landed census rules that class ABSENT
    # (largest live collision is two), and a specimen for an ABSENT row is RED
    # under AC-3(i). Structurally, a flat corpus's collision IS a divergence —
    # the census's own ONE-or-TWO ruling.
    "@Quillam Ostrivane Lumbrek.md": NoteSpec(
        declared_type="person",
        fields=_person("Quillam Ostrivane Lumbrek"),
    ),
    "@25 Corvallen Ravensby-3rd Pellworth-Wexlund 8.md": NoteSpec(
        declared_type="person",
        fields=_person("25 Corvallen Ravensby-3rd Pellworth-Wexlund 8"),
        shape_classes=("postal_address_in_name",),
        verdict=Verdict(kind="loads"),
    ),
    # Declares NO `phones`, which is what decides its verdict: the door's
    # `allow_phone_sentinel` (`name_gate.py:355-358`) passes a digit-named note
    # that ALSO declares phones, and this specimen exists to exercise the branch
    # it is the specimen OF. `.pattern` is the RECORD's `pattern` field
    # (`name_validation.py:285`), never its `branch_id`.
    "@+447700900123.md": NoteSpec(
        declared_type="person",
        fields=_person("+447700900123"),
        shape_classes=("pure_digit",),
        verdict=Verdict(kind="refusal", pattern="pure_digit_name"),
    ),
    # The two AC-1(c) discriminators: `shape_classes = ()` because the landed
    # census rules both branches ABSENT, `discriminator` because AC-1(c) still
    # obliges them and asks a question about the DOOR.
    "@Perrowin Tessamund Drostane.md": NoteSpec(
        declared_type="person",
        fields=_person("Perrowin -> Tessamund Drostane"),
        discriminator="arrow_connective",
    ),
    "@Yolvenna Brindlecote Skarnell.md": NoteSpec(
        declared_type="person",
        fields=_person("Yolvenna/Brindlecote Skarnell"),
        discriminator="path_hostile",
    ),
    "@Morvette Harkwell.md": NoteSpec(
        declared_type="person",
        fields=_person("Morvette Harkwell"),
        # AC-5(b) clause 3: a value for a key no model declares is an identity
        # position BY DEFAULT, with no manifest flag to opt out.
        undeclared={"introduced_by": "Voxleaf"},
    ),
    "@Caldreth Zebrant.md": NoteSpec(
        declared_type="person",
        fields=_person("Caldreth Zebrant", aliases=["Zebrant"]),
    ),
    "@Elowick Varnholt.md": NoteSpec(
        declared_type="person",
        fields=_person(
            "Elowick Varnholt",
            emails=["elowick@example.com"],
            phones=["+44 7700 900456"],
        ),
    ),
    "@Isolde Quenlaw.md": NoteSpec(
        declared_type="person", fields=_person("Isolde Quenlaw")),
    "@Tessamund Ferrigan.md": NoteSpec(
        declared_type="person", fields=_person("Tessamund Ferrigan")),
    "@Ravensby Ostrivane.md": NoteSpec(
        declared_type="person", fields=_person("Ravensby Ostrivane")),
    "@Skarnell Dalquest.md": NoteSpec(
        declared_type="person", fields=_person("Skarnell Dalquest")),
    "@Pellworth Brenvik.md": NoteSpec(
        declared_type="person", fields=_person("Pellworth Brenvik")),
    "@Wexlund Tarnquil.md": NoteSpec(
        declared_type="person", fields=_person("Wexlund Tarnquil")),
    "@Kelmarra Marrowyn.md": NoteSpec(
        declared_type="person", fields=_person("Kelmarra Marrowyn")),
    "@Fennwick Drostane.md": NoteSpec(
        declared_type="person", fields=_person("Fennwick Drostane")),

    # ---- company ----------------------------------------------------------
    "@Voxleaf Ltd.md": NoteSpec(
        declared_type="company",
        fields=_company("Voxleaf Ltd", industry="software"),
        roundtrip_representative=True,
    ),
    "@Ulvestre Group.md": NoteSpec(
        declared_type="company", fields=_company("Ulvestre Group")),
    "@Brindlecote Nimbrook.md": NoteSpec(
        declared_type="company", fields=_company("Brindlecote Nimbrook")),
    "@Ashquill Ostrakine.md": NoteSpec(
        declared_type="company", fields=_company("Ashquill Ostrakine")),
    "@Nimbrook Limited.md": NoteSpec(
        declared_type="company", fields=_company("Nimbrook Limited")),
    "@Quenlaw Inc.md": NoteSpec(
        declared_type="company", fields=_company("Quenlaw Inc")),

    # ---- meeting ----------------------------------------------------------
    "Meeting 20260104 - Voxleaf Kelmarra.md": NoteSpec(
        declared_type="meeting",
        fields=_meeting("2026-01-04", ["Thrandell Ibberly", "Isolde Quenlaw"],
                        ["roadmap", "hiring"], "mtg-a-voxleaf"),
        roundtrip_representative=True,
    ),
    "Meeting 20260118 - Thrandell Ibberly.md": NoteSpec(
        declared_type="meeting",
        fields=_meeting("2026-01-18", ["Thrandell Ibberly"], ["catch up"],
                        "mtg-b-thrandell")),
    "Meeting 20260205 - Ashquill Ostrakine.md": NoteSpec(
        declared_type="meeting",
        fields=_meeting("2026-02-05", ["Morvette Harkwell", "Caldreth Zebrant"],
                        ["pricing"], "mtg-c-ashquill")),
    "Meeting 20260301 - Brindlecote Ulvestre.md": NoteSpec(
        declared_type="meeting",
        fields=_meeting("2026-03-01", ["Elowick Varnholt"], ["renewal"],
                        "mtg-d-brindlecote")),
    "Meeting 20260315 - Morvette Isolde.md": NoteSpec(
        declared_type="meeting",
        fields=_meeting("2026-03-15", ["Isolde Quenlaw", "Morvette Harkwell"],
                        ["review"], "mtg-e-morvette")),

    # ---- book -------------------------------------------------------------
    "Ashquill Nimbrook - Perrowin Skarnell.md": NoteSpec(
        declared_type="book",
        fields=_book("Ashquill Nimbrook", "Perrowin Skarnell",
                     description="a placeholder description", status="read",
                     rating="4", isbn=RESERVED_ISBN, publisher="Ostrakine Ltd",
                     publication_year="2019", date_finished="2026-02-20"),
        roundtrip_representative=True,
    ),
    "Drostane Caldreth - Yolvenna Harkwell.md": NoteSpec(
        declared_type="book",
        fields=_book("Drostane Caldreth", "Yolvenna Harkwell")),
    "Ostrakine Lumbrek - Morvette Quenlaw.md": NoteSpec(
        declared_type="book",
        fields=_book("Ostrakine Lumbrek", "Morvette Quenlaw")),
    "Sennaby Varnholt - Caldreth Ravensby.md": NoteSpec(
        declared_type="book",
        fields=_book("Sennaby Varnholt", "Caldreth Ravensby")),

    # ---- watch / explore / gift-idea / exploration -------------------------
    # No repository and therefore no glob: these four types are AC-2's
    # parser-level business alone and are outside AC-4 entirely.
    "Drostane Yolvenna.md": NoteSpec(
        declared_type="watch",
        fields=_watch("Drostane Yolvenna", media_type="film",
                      director="Perrowin Skarnell", year="2021",
                      status="watched", rating="5",
                      streaming_service="Nimbrook",
                      recommended_by="Isolde Quenlaw",
                      date_watched="2026-02-14"),
        roundtrip_representative=True,
    ),
    "Varnholt Ferrigan.md": NoteSpec(
        declared_type="watch", fields=_watch("Varnholt Ferrigan")),
    "Tarnquil Pellworth.md": NoteSpec(
        declared_type="watch", fields=_watch("Tarnquil Pellworth")),

    "Caldreth Elowick.md": NoteSpec(
        declared_type="explore",
        fields=_explore("Caldreth Elowick", subtype="link",
                        source="Morvette Harkwell", status="exploring"),
        roundtrip_representative=True,
    ),
    "Nimbrook Ravensby.md": NoteSpec(
        declared_type="explore", fields=_explore("Nimbrook Ravensby")),
    "Ibberly Zebrant.md": NoteSpec(
        declared_type="explore", fields=_explore("Ibberly Zebrant")),

    "Morvette Quenlaw.md": NoteSpec(
        declared_type="gift-idea",
        fields=_gift("Isolde Quenlaw", "Thrandell Ibberly"),
        roundtrip_representative=True,
    ),
    "Harkwell Isolde.md": NoteSpec(
        declared_type="gift-idea",
        fields=_gift("Morvette Harkwell", "Caldreth Zebrant")),
    "Ostrivane Elowick.md": NoteSpec(
        declared_type="gift-idea",
        fields=_gift("Elowick Varnholt", "Tessamund Ferrigan")),

    # `exploration` is the type with ZERO test references anywhere under
    # `tests/` before this item (P4); this is the first fixture anyone has
    # authored for it, and `related:` is an identity position (AC-5(b)).
    "Harkwell Tessamund.md": NoteSpec(
        declared_type="exploration",
        fields=_exploration("Harkwell Tessamund",
                            related=["[[Voxleaf Kelmarra]]",
                                     "[[Thrandell Ibberly]]"],
                            origin="a conversation about tooling"),
        roundtrip_representative=True,
    ),
    "Sennaby Halvorne.md": NoteSpec(
        declared_type="exploration", fields=_exploration("Sennaby Halvorne")),
    "Dalquest Corvallen.md": NoteSpec(
        declared_type="exploration", fields=_exploration("Dalquest Corvallen")),

    # ---- the skip specimens -----------------------------------------------
    # `declared_type` is what the note makes LEGIBLE, which is what ownership is
    # decided on: `FrontmatterParseError` carries `declared_type=None` always
    # (`errors.py:65-67`) and a `UnicodeDecodeError` carries the attribute not at
    # all, so both fall to `_owns(None)`.
    "@Halvorne Sennaby.md": NoteSpec(declared_type=None),
    "Meeting 20260212 - Zebrant Dalquest.md": NoteSpec(declared_type=None),
    "@Ferrigan Ostrakine.md": NoteSpec(declared_type="person"),
    # The ONE non-UTF-8 member (§1.3 rule 4) — the only spelling of `unreadable`
    # that survives git. EXEMPT from AC-5(b)'s token scan and reviewed instead:
    # its complete bytes are declared here in LOWERCASE hex (so the literal
    # itself yields no extracted token) and asserted byte-equal.
    "@Isolde Varnholt.md": NoteSpec(
        declared_type=None,
        # ONE unbroken literal on purpose: AC-5(a) asserts each declared hex
        # literal OCCURS in the reach and EXCISES it before the span walk, and
        # implicit string concatenation would leave neither true of the source.
        raw_bytes_hex="2d2d2d0a747970653a20706572736f6e0a6e616d653a202249736f6c6465205661726e686f6c74220a746167733a205b706572736f6e5d0a2d2d2d0a0a2323204e6f7465730a0a6e6f742076616c6964207574662d383a20fffefd0a",  # noqa: E501
    ),
}


#: `{repository type_name: {filename: reason}}` — keyed by REPOSITORY, never a
#: union. Ownership is a joint function of the FILENAME and the error's
#: `declared_type` (`base.py:258-275`), so the same untyped specimen legitimately
#: appears in two repositories' mappings at once and in neither of the other
#: two's; a union manifest cannot express that and cannot go red when a
#: regression moves a skip between owners. The reason VALUES are the imported
#: constants; WHICH constant a filename maps to stays the hand-declared oracle.
SKIPS: dict = {
    "person": {
        "@Halvorne Sennaby.md": MALFORMED_FRONTMATTER,
        "@Isolde Varnholt.md": UNREADABLE,
        "@Ferrigan Ostrakine.md": SCHEMA_DRIFT,
    },
    # Both untyped classes, because `@*.md`'s stem is `@*` and `_owns(None)`
    # therefore returns True for company exactly as it does for person. The
    # schema-drift specimen declares `person`, so it is NOT company's.
    "company": {
        "@Halvorne Sennaby.md": MALFORMED_FRONTMATTER,
        "@Isolde Varnholt.md": UNREADABLE,
    },
    # The second planted discriminator: an untyped specimen under the OTHER
    # owning glob, so a stub that records untyped skips in one repository only
    # is distinguishable from the real rule.
    "meeting": {
        "Meeting 20260212 - Zebrant Dalquest.md": MALFORMED_FRONTMATTER,
    },
    # EMPTY on purpose and asserted so: `*.md`'s stem is exactly `*`, so the
    # catch-all glob DECLINES ownership of every untyped failure by design. This
    # is the only assertion in the suite that exercises that arm.
    "book": {},
}

#: `{repository type_name: len(repo.get_all())}` — the CACHE quantity and never
#: the file count: `load()` counts files that produced an entity while
#: `get_all()` returns `list(self._cache.values())`, and the cache is keyed by
#: `_get_cache_key`. The three-filename collision therefore contributes THREE to
#: `load()` and ONE here, which is where a declared number is most likely to be
#: off by two.
LOADABLE: dict = {
    "person": 20,      # 22 person files, three of which share one stored name
    "company": 6,
    "meeting": 5,      # six `Meeting *.md` files, one of them a malformed skip
    "book": 4,
}

#: `((query, expected Person.name), ...)` for `PersonRepository.resolve` — the
#: exact-name, alias, email and phone arms of the cascade.
RESOLVABLE: tuple = (
    ("Thrandell Ibberly", "Thrandell Ibberly"),
    ("Zebrant", "Caldreth Zebrant"),
    ("elowick@example.com", "Elowick Varnholt"),
    ("+447700900456", "Elowick Varnholt"),
)

#: `{entity type: field names whose value IS a person's or an organisation's
#: name}` — AC-5(b)'s three clauses applied field by field against `models.py`,
#: the pass P14 records. HAND-DECLARED because `models.py` declares FIELDS and
#: nothing in it declares which of them carry identity: unlike AC-2's
#: `TYPE_TO_MODEL`, AC-3's `branch_id`s and AC-4's repository set there is no
#: population to read, and the classification is judgment.
#:
#: Clause 2's declared OVER-CONSTRAINT is the four entity `title` fields — a
#: book, a film, a link and a living document are not people or organisations,
#: so clause 1 does not reach them and they are here ON PURPOSE. Clause 3's
#: undeclared keys are outside this table by construction and are read from each
#: note's `undeclared` mapping instead.
#:
#: Excluded and argued: `Person.title` (a JOB title, names nobody),
#: `Meeting.topics`, `Exploration.origin`, `Exploration.graduated_to` (sentences
#: and a project, not names). `Meeting` declares no `title` field at all.
IDENTITY_FIELDS: dict = {
    "person": ("name", "aliases", "company"),
    "company": ("name",),
    "book": ("title", "author", "publisher"),
    "watch": ("title", "director", "streaming_service", "recommended_by"),
    "explore": ("title", "source"),
    "gift-idea": ("for_person", "source"),
    "meeting": ("attendees",),
    "exploration": ("title", "related"),
}

#: Every constructed given name, surname and company word the specimens are
#: built from. A SUBSET of the census's pool table (AC-5(c) is a containment,
#: one direction), and every member occurs as an extracted token in at least one
#: IDENTITY position — declared only where the corpus uses it, which is what
#: makes the non-vacuity clause satisfiable by construction.
NAME_POOL = frozenset({
    "Ashquill", "Brenvik", "Brenvik-Tarnquil", "Brindlecote", "Caldreth",
    "Corvallen", "Dalquest", "Drostane", "Elowick", "Fennwick", "Ferrigan",
    "Halvorne", "Harkwell", "Ibberly", "Isolde", "Kelmarra", "Kelmarrä",
    "Lumbrek", "Marrowyn", "Morvette", "Nimbrook", "Oskaline", "Ostrakine",
    "Ostrivane", "Pellworth", "Pellworth-Wexlund", "Perrowin", "Quenlaw",
    "Quillam", "Ravensby", "Sennaby", "Skarnell", "Søréna", "Tarnquil",
    "Tessamund", "Thrandell", "Ulvestre", "Varnholt", "Voxleaf", "Wexlund",
    "Yolvenna", "Zebrant",
})

#: The corruption classes' own non-identifying furniture — the package's OWN
#: calendar/arrow/transcript prefix vocabulary, the union across
#: `name_cleaning.py:46`, `:54` and `:55`. FIXED BY ENUMERATION in AC-5(b) and
#: asserted equal to that literal, so it cannot grow without an AC change; it
#: carries no occurrence obligation of any kind, which is the round-4 fix.
CONNECTIVE_SET = frozenset({"Me", "My", "Dave"})

#: The ordinary English of the note bodies plus this module's own identifiers,
#: docstring and comment vocabulary. Reachable ONLY from free-prose positions
#: and asserted DISJOINT from every identity token, so adding a surname here
#: buys nothing whatsoever for a `name:` value, an alias, a title field or a
#: filename stem — which is what makes the position split a wall rather than a
#: bucket.
PROSE_ALLOWLIST = frozenset({
    # The body section headings `ENTITY_BODY_CONFIG` declares.
    "Actions", "Commitments", "Context", "Current", "Decisions", "Discuss",
    "Documents", "Key", "Next", "Notable", "Notes", "Open", "Out", "People",
    "Questions", "Quotes", "Ruled", "Steps", "Summary", "Thinking", "Timeline",
    "To", "Topics",
    # This module's own identifiers, docstring and comment vocabulary — the
    # residue of the same scan, taken over this file AS IT STANDS.
    "A", "ABSENT", "AC", "ADDS", "ALLOWLIST", "ALSO", "AND", "An", "BODY",
    "BY", "Both", "Byte-copy", "CACHE", "CALENDAR", "CONFIG", "CONNECTIVE",
    "CORPUS", "CORPUS-RELATIVE", "COUPLING", "Clause", "DECLARED", "DECLINES",
    "DEFAULT", "DIGEST", "DISJOINT", "DOOR", "DRIFT", "Declares", "Design",
    "Dict", "E", "EMPTY", "ENTITY", "ENUMERATION", "EQUALITY", "EXCISES",
    "EXEMPT", "Editing", "English", "Every", "Excluded", "Exploration",
    "FIELDS", "FILENAME", "FIXED", "FRONTMATTER", "False",
    "FrontmatterParseError", "GENERIC", "HAND", "HAND-DECLARED",
    "HAND-WRITTEN", "Hex", "IDENTITY", "IDs", "IS", "ISBN", "It", "Its", "JOB",
    "Keyed", "LEGIBLE", "LOADABLE", "LOWERCASE", "Load", "Load-bearing",
    "MALFORMED", "MEASURED", "MODEL", "Meeting", "NAME", "NAMED", "NEVER",
    "NO", "NOT", "NOTES", "NUL", "NUL-framed", "NameGateRefusal", "Never",
    "No", "None", "NoteSpec", "OCCURS", "OF", "ON", "ONE", "ONE-or-TWO",
    "ONLY", "OR", "ORG", "OTHER", "OVER-CONSTRAINT", "OWN", "One", "Optional",
    "Ownership", "P", "POOL", "POSIX", "PREFIX", "PROSE", "PURPOSE", "Path",
    "AS", "IT", "STANDS", "Person", "PersonRepository", "RE", "RECORD's",
    "RED", "REPOSITORY",
    "RESERVED", "RESOLVABLE", "ROOT", "Reachable", "Read", "Reading",
    "Regenerating", "SAME", "SCHEMA", "SET", "SKIPS", "SUBSET", "SUFFIXES",
    "Structurally", "THERE", "THREE", "TO", "TYPE", "The", "There", "This",
    "Three", "Tier", "True", "Two", "UNREADABLE", "UnicodeDecodeError",
    "VALUES", "VAULT", "Verdict", "Verdicts", "WHICH", "WI", "What", "Where",
    "Which", "ZERO",
})


def materialize_vault(dest) -> Path:
    """Byte-copy the flat corpus into a caller-supplied directory.

    ADDS, never empties: a second call against the same `dest` overwrites each
    corpus member with identical bytes and leaves everything else in that
    directory alone. There is no `rmtree`, no glob-and-unlink and no "clean
    first" branch, and none may be added — emptying a caller-supplied directory
    is a destructive act a fixture helper has no business performing, and
    AC-1(b) asserts both halves.

    Never `shutil.copy2` (which carries mode and mtime the corpus does not
    declare), never `read_text`/`write_text` (which would raise on the non-UTF-8
    member and normalise line endings on the others), and never
    `write_markdown_file`, `write_frontmatter`, `repo.save()` or `create_stub` —
    those route through `gate_write` (`writer.py:252-253`), which is exactly
    what refuses half of this corpus.
    """
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    for src in sorted(CORPUS_ROOT.iterdir()):
        if src.is_file():
            (dest / src.name).write_bytes(src.read_bytes())
    return dest


def corpus_digest(root: Path = CORPUS_ROOT) -> str:
    """`sha256` over the sorted (filename, bytes) pairs, each NUL-framed.

    The framing is not decoration: without a separator, a rename that moves
    bytes between the name field and the content field produces the same digest.
    The walk is the SAME walk `materialize_vault` performs, which is what lets
    AC-1(b) compare the digest over the materialized tree against this constant
    with no second traversal rule to keep in step.
    """
    digest = hashlib.sha256()
    for path in sorted((p for p in Path(root).iterdir() if p.is_file()),
                       key=lambda p: p.name):
        digest.update(path.name.encode("utf-8"))
        digest.update(b"\x00")
        digest.update(path.read_bytes())
        digest.update(b"\x00")
    return digest.hexdigest()
